# Generated by Django 5.1.2 on 2024-10-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_apertura', models.DateTimeField()),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_ventas', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('tipo_venta', models.CharField(max_length=30)),
                ('forma_pago', models.CharField(max_length=30)),
                ('tipo_comprobante', models.CharField(max_length=30)),
                ('numero_comprobante', models.IntegerField(unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
