# Generated by Django 5.1.2 on 2024-10-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Credito'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('RECIBO', 'Recibo'), ('FACTURA', 'Factura'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('MINORISTA', 'Minorista'), ('MAYORISTA', 'Mayorista')], max_length=30),
        ),
    ]
