# Generated by Django 5.1.2 on 2024-10-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_forma_pago_alter_venta_tipo_comprobante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('id_mayorista', models.AutoField(primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=30)),
                ('direccion', models.TextField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')])),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('categoria', models.CharField(choices=[('PAN', 'Panificación'), ('PAS', 'Pastelería')], max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_apertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuit',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
