# Generated by Django 5.1.2 on 2024-11-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='ventas.empleado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='mayorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mayorista', to='ventas.mayorista'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista')], default='Mayorista', max_length=30),
        ),
    ]
