# Generated by Django 5.1.2 on 2024-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_remove_venta_producto_alter_venta_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('CANCELADA', 'Cancelada')], default='Registrada'),
        ),
    ]
