# Generated by Django 5.1.2 on 2024-11-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_detalleventa_producto_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('CANCELADA', 'Cancelada')], default='REGISTRADA'),
        ),
    ]
