# Generated by Django 5.1.2 on 2024-11-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('PANIFICACION', 'Panificación'), ('PASTELERIA', 'Pastelería')], max_length=30)),
                ('stock', models.PositiveIntegerField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='Activo')),
            ],
        ),
    ]
